project:
  type: website
  output-dir: docs

website:
  title: "学习资源新模式"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 简介
    
      
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "周忠国&孟祥芹"
      - text: "邮箱:zhghou@hhu.edu.cn"
      - text: "****目录****"
      - text: "<strong>新模式简介</strong>"
        href: index.qmd
      - section: "<strong>案例</strong>"
        contents:
          - zhishi.qmd
          - jieti.qmd
          - suzhi.qmd
      - section: "<strong>漫游数学美不胜收</strong>"
        contents: 
          - taylor.qmd
          - scfc.qmd
          
      
format:
  html:
    theme: cosmo
    
    css: styles.css
    toc: true
    number-sections: true
    lang: zh-CN  
    

editor: visual
lang: zh-CN 
