---
title: "成果导向与菜单式导航<br>---数字化学习资源建设新模式"
---

2025年9月23日

**说明**   

- 我们提出了成果导向与菜单式导航数字化学习资源模式，并给出了一些案例，希望为教师和学生提供一种提高学习和教学效率的资源组织模式，更多人参与进来，有更多的人从中受益，让个性化学习，终身学习，随时随地学习，开放学习成为可能。



- 此模式能够降低学习难度。

- 不需要专门的技术和设备，易于建设，降低开发、建设难度。

- 此模式侧重培养学生分析、解决问题的能力，教学生学会学习。

- 以成果为导向，把知识、能力和素质的目标要求分解并设计成菜单，即任务点。

- 利用菜单的折叠隐藏功能实现地图导航。

- 学习就像打游戏过关一样，让学生能明确认识到自身不足之处与困难所在，从而采取针对性的学习、训练，进而提高自身能力。






# 理想的数字化资源

- 美好图景：提供个性化学习、终身学习、因材施教、无门槛学习。



::: {.callout-tip collapse="true" icon="true"}
## 1．能够降低学习难度(<font color="red">点击此处可展开或隐藏内容</font>)。

- 仅仅把电子讲稿、课件、微视频、案例、在线课程推荐给学生，并没有降低学习的难度。

- 微视频、慕课、知识图谱等碎片化的知识展现与学习方式让学生很难协调、把握知识的整体性，往往导致只见树木，不见森林，无形中增加了学习的难度。

:::
::: {.callout-tip collapse="true" icon="true"}
## 2．能够降低学习资源的建设、开发难度。

- 教师不需要专门的学习或培训就能比较容易参与到资源的建设中来。

- 现实情况是有些新技术也不容易掌握，使用有难度，在“一次开发”和“二次整合使用”方面均需花费大量的时间与精力。

:::
::: {.callout-tip collapse="true" icon="true"}
## 3．能够提供直接培养、提高学生某些方面能力的材料。

- 传统的学习资源是以内容为导向，按章节组织材料的，主要是传授知识。在此过程中，“潜移默化”地培养能力。

- 未来的教育或学习资源是以“直接”地培养、提高分析与解决问题的能力为目的。或者是培养、训练某项专门的能力为目的。

:::
::: {.callout-tip collapse="true" icon="true"}
## 4. 其它要求

- 数字化学习资源尽量开源，触手可及，容易获取。

- 要能够提供因材施教，个性化的学习，学生可以根据自身基础灵活选取学习路径、最好能够给出学生学习结果的准确评价。

- 学习资源适合不同场景，如预习、学习、复习，讨论式等，使用模块化设计，学生只需根据需要选择相应模块，不需为不同目的和场景重复进行资源建设。

:::





# 成果导向与菜单式导航数字化学习资源是什么

- 学习资源就像一张地图，一开始很多细节是隐藏的，在学生查看、学习时才会展开，显示。

- 在整个学习过程中，学生根据自身需要可以通过地图导航在不同菜单之间跳转、切换进行学习。

- 每个菜单既是要学习的内容也是要完成的任务点（分目标）。

::: {.callout-note collapse="true" icon="true"}
## 是一本电子书

- 成果导向与菜单式导航数字化学习资源是一种电子资源，可以制作成网站、网页、用于教或学的课件、甚至电子书的形式。


:::
::: {.callout-note collapse="true" icon="true"}
## 以成果为导向

- 学习资源里面的学习内容和学习步骤是以学习成果，学习目标（包括知识、能力和素质）为导向设计成菜单，进行组织的。

:::
::: {.callout-note collapse="true" icon="true"}
## 菜单式导航

- 菜单的内容可以折叠隐藏、按需要再展开显示，分层次的菜单形成一个地图，对学习内容进行导航。


:::
::: {.callout-note collapse="true" icon="true"}
## 分解任务点

- 学习内容按照知识点或解决问题的步骤，按不同层次分解成不同级别小知识点或任务点，称为菜单或标题.

- 使用者根据自己的基础、学习目标等情况，在菜单地图导航的帮助下，选择并点击相应的菜单，这时被折叠起来、隐藏在菜单内部的内容就可以展开，

- 使用者可以学习这些内容，完成任务，此部分内容学完后可以重新折叠起来，变为隐藏状态。

:::



# 成果导向与菜单式导航数字化学习资源的特点与优点

::: {.callout-important collapse="true" icon="true"}
## 菜单式设计降低学习难度；让学习因人而异，实现因材施教

- 把知识点按由易到难，由浅入深做好层次分析，把任务点制作成小标题，也就是菜单，然后一一罗列出来。每个小标题继续分层次，直到这个标题比较简单易学或仅含一个知识点为止。

- 把一次课的内容分解为若干不同层次、不同级别的小知识点，设置为菜单。每个菜单是知识点的一个侧面或某个更小的相关知识点，菜单上会提出具体的要求或问题，让学生回答，每个菜单被点击展开后，里面包含的内容负责解决此菜单提出的问题。

- 分解后的菜单，标题非常多，会导致碎片化。这时通过菜单内容的隐藏与显示功能，按不同层次，重新整合菜单，把碎片化的菜单组成为一个有机的整体。

- 学生根据自身的情况选择相应的菜单学习，已掌握的或对自己来说不要求掌握的内容可以快速通过，不用把标题展开；没掌握的内容可以展开标题，深入学习。




:::





::: {.callout-important collapse="true" icon="true"}
## 地图导航帮助学生快速学习，明白在学什么

- 碎片化设计降低了学习难度，能清晰展示解决问题的过程，是化整为零；菜单的隐藏式设计实现了提纲挈领，是化零为整。把局部与整体，分解与整合很好地结合起来了。

- 菜单分多个层次，用类似地图的方式组织，大地图里面有小地图，由浅到深，由粗略到细致，一开始每个菜单内部的学习内容是隐藏起来的，只显示最外层的菜单，根据使用者的选择展现可大可小的视角。一句话，在地图导航的帮助下，学生想学哪个菜单对应的内容，就可以方便地找到这个菜单，直接展开学习。在学习过程中，可以随时选择、切换学习内容，像查看电子地图一样，可以从整体看地形地貌、区域分布，也可以深入某个感兴趣的地区细细研究。



- 地图导航，指导学习的全过程。每个菜单实际上是它内部内容的概括与总结，由于具体内容都是隐藏的，就使得学生对脉络一目了然，天然地具有宽广的视角。学生选择某个菜单学习的过程，就是从整体不断展开然后选择某个局部进行学习，所以他能够一直从整体上明白自己在学什么，正在学习的内容处于整个内容里面的位置，不致于只见树木，不见森林。


:::
::: {.callout-important collapse="true" icon="true"}
## 过关式学习让学生明确认识自身不足之处与困难所在

- 成果导向与菜单式导航数字化学习资源让学习就像打游戏过关一样，每个菜单代表一个知识点或某项能力，可以看成一个个任务点，如果学生能够解决菜单上提出的具体要求或问题，则代表掌握这部分内容，完成这个任务，过关。如不能则表示没掌握，可以展开此菜单，学习这部分内容；也可以先承认结论成立，后面需要时再来学习或证明。

- 对不同的学生来说，可以根据菜单采取针对性的学习、训练解决困难。



:::
::: {.callout-important collapse="true" icon="true"}
## 学习、考试、评价的统一

- 菜单即任务点，是按学习目标设置的，完成了任务点，即掌握了内容，达到了学习目标的要求。因此学习过程就是考试过程，就可以进行评价。

- 如果在学习资源中添加完成任务点的统计功能，那么就能给出学生的评价，实际上，这个评价非常细致、个人化，每个人掌握了多少？掌握了什么？哪里是薄弱环节，在知识与能力方面等等都能给出分析，而不仅仅是一个分数。这对学生了解自身，从而采取针对性的学习、训练、提高自身大有帮助。

- 这种学习以及评价模式完全是以学习成果为导向的，能够回答: 如何有效地帮助学生取得这些学习成果？如何知道学生已经取得了这些学习成果？

:::
::: {.callout-important collapse="true" icon="true"}
## 知识、能力、素质的统一

- 在一门课程的学习目标，学习成果中既有知识的学习也有能力的培养，还有提升素质的要求。

- 把解决问题的思路分析，可以制作成一些菜单或任务点，通过提问的方式把分析过程一一展现给学生，引导学生思考，帮助学生把步骤分析清楚，让他们模仿，进而训练、提高相应解决问题的能力。

-  在成果导向与菜单式导航数字化学习资源中，每个题目都可以这样制作，学生各取所需，按需学习。每个题目都可以用明显的方式训练、培养学生的分析、解决问题的能力。

- 成果导向与菜单式导航数字化学习资源每个菜单里面的内容、步骤，甚至菜单的设计、展示本身就在教学生如何分析，如何学习。 学习一个菜单的内容的同时也在培养能力。

:::
::: {.callout-important collapse="true" icon="true"}
## 开放共享、人人参与、触手可及、迭代升级

- 成果导向与菜单式导航数字化学习资源以网页、网站的形式组织，可以制作成开放共享的资源，每个人可以是学习者也可以是建设者，根据反馈、互动不断迭代升级。

- 网页、网站的形式也让学习资源的学习和建设触手可及，打破了空间和时间的限制。随时，随地，想学什么，就学什么。

:::
::: {.callout-important collapse="true" icon="true"}
## 其它特点

- 成果导向与菜单式导航数字化学习资源是网页格式，随时随地可以插入超链接，引用图片、视频、PPT、动画、其它网页等等学习资源，使学习资源更为丰富，灵活多样，满足不同要求。

- 在菜单上加上表示难度、重要程度、学习要求的符号让重点，难点层次分明。让学生知道每个知识点需要掌握到什么程度，是否重点等。每个菜单上加上进度条，记录学习进度。

- 网页格式文档在不同操作系统，不同平台都可以使用。


:::

# 成果导向与菜单式导航数字化学习资源的创新点

::: {.callout-warning collapse="true" icon="true"}
## 折叠隐藏的的创新使用

- 成果导向，菜单导航，任务点设计，内容折叠这些概念并不新鲜，但是把这些概念统一起来，组织成一个容易制作建设并适合教与学的数字化学习资源是本文最大的创新之处。

:::

::: {.callout-warning collapse="true" icon="true"}
## 导航的创新使用

- 传统的数字化资源也有目录进行导航、跳转；网页的一些内容也可折叠。表面上看和成果导向与菜单式导航数字化学习资源类似，但两者有本质上的差异。这也是我们提出成果导向与菜单式导航数字化学习资源这个概念的创新点。




- 传统的目录式导航的作用仅仅是一个定位，把当前视角定位、切换到需要的位置。目录一般是以内容为导向，按章节设置，一般是名词，导航相当于查找某个知识点。


-  比如一些百科全书的网站，导航只是定位到某个知识点，并没有、也不能帮助学生学习这个知识点。


- 成果导向与菜单式导航数字化学习资源是以成果导向的，菜单设置得更多，更细；不仅仅是按章节小节分解后的标题，同时还是一个个任务点。一般会提出问题和要求，把原来的问题分解成几个小问题，小步骤。

-  这种设计使得学生导航定位的过程就是帮助他们分析、学习、完成任务的过程。把导航与学习统一起来，更利于达到学习目标，提高学习效率。


:::
::: {.callout-warning collapse="true" icon="true"}
## 培养能力的创新

- 传统的数字化资源普遍缺乏直接、有针对性的培养能力的部分。

- 对题目的思路怎么来的，缺少具体的分析，怎么一步步解题。

- 一个知识点要怎么分析，怎么学习，怎么概括等内容老师在课堂上会讲，这正是学生需要的。但传统数字化资源的设计理念和设计方法导致了它们很少也很难提供这些东西。

- 成果导向与菜单式导航数字化学习资源恰恰解决了这个困难。通过把任务点菜单导航与菜单的隐藏、折叠结合起来，完美地再现解决问题的整个过程，再现课堂教学过程。培养能力部分是成果导向与菜单式导航数字化学习资源新增的内容，是制作、设计的重点。


:::
::: {.callout-warning collapse="true" icon="true"}
## 整体与局部的创新融合

- 菜单导航与菜单的隐藏相结合在不同视角之间切换，牢牢把握学生的焦点。

- 比如，一道数学题，整个解题过程需要好几张幻灯片，里面的细节很繁琐。在学习过程中，可能会看到后面忘了前面，或不知各个细节在干什么。

- 如果把关键步骤、整个解题过程设计成几个菜单，细节隐藏在菜单里面，层次分明，使得学生始终聚焦在自己要解决的菜单上，思路就会清晰许多。

:::




# 成果导向与菜单式导航数字化学习资源的建设与制作

::: {.callout-note collapse="true" icon="true"}
## 软件

- 利用开源科技出版系统quarto制作。

:::
::: {.callout-note collapse="true" icon="true"}
## 步骤

-  第一步，把知识点、学习目标分层次，把题目的思路分析等分为小步骤，形成不同层次的菜单–标题，菜单内部的内容补充完整。相当于把真实的课堂讲授过程重现。


- 第二步实现每个菜单的折叠功能，标题下的内容可以根据需要隐藏或展开。在quarto中，用“Callout Blocks”的“collapse”选项可以简单的实现折叠。具体可以参考网站上的quarto使用说明文档。

- 菜单的设计起关键的作用。需要设计者对整个课程、对每一部分，甚至每个知识点的安排都要有全盘的认识和考虑。不仅如此，对于题目的逐步思路分析、设计引导学生一步步的思考的菜单都需要精心地准备。

- 这部分需要花较大资源和精力制作。要想设计、建设一个真正实用的成果导向与菜单式导航数字化学习资源，不是一蹴而就的。要坚持开放共享、人人为我，我为人人的理念，可以从一个个知识点、一个个题目开始，不断添加、整合，在使用中迭代、优化升级。



:::

# 几个例子



- 可以点击网页左边的"案例"按钮查看.