---
title: "泰勒公式"
---

$$\begin{aligned}
    f(x)&=P(x)+R(x)\\
    &=主要部分(\color{blue}{近似值})+次要部分(\color{blue}{误差}).
\end{aligned}   $$

-   泰勒公式是研究函数的一个威力极大的工具.

-   把一个复杂函数用一个简单函数来近似.

-   能够把复杂问题变成简单问题!

::: {.callout-note collapse="true" icon="true"}
## 例子

例如函数$e^x$, 在$x=0$附近: $$
e^x=1+x+o(x).
$$ 则有时抓住$1+x$就够了.
:::

# 泰勒公式的本质与关键

::: {.callout-tip collapse="true" icon="true"}
## 泰勒公式的本质

泰勒公式就是把$f(x)$分解成两个函数的和, $$\begin{aligned}
    f(x)&=P(x)+R(x)\\
    &=主要部分(\color{blue}{近似值})+次要部分(\color{blue}{误差}),
\end{aligned}   $$

-   $P(x)$是一个简单的函数, 是$f(x)$的主要部分, 可以作为近似值;
-   $R(x)$是一个误差, 是$f(x)$的次要部分, 根据需要, 可以小于任意预先给定的误差.
:::

::: {.callout-important collapse="true" icon="true"}
## 泰勒公式的关键

-   要能把近似函数$P(x)$求出来,

-   要能准确估计误差$R(x)$的大小.

-   如果要求的误差不同, 则相应的近似函数$P(x)$也不同, 所以$f(x)$的泰勒公式实际上是一组公式.
:::

# 简单的函数$P(x)$

::: {.callout-note collapse="true" icon="true"}
## 什么样的函数简单?

$$
P_n(x)=a_0+a_1x+\cdots+a_nx^n
$$ 比较简单, 原因

-   是线性函数$ax+b$的推广.
-   各种计算及求导容易.
-   一元$n$次方程恰好有$n$个根.
:::

::: {.callout-warning collapse="true" icon="true"}
## $P(x)$怎么会成为$f(x)$的主要部分?

-   如果两个函数在某个固定点处的函数值相等, 一阶导数相等, 各阶导数都相等, 则可以想象在此点的邻域, 这两个函数会长得很像, 几乎一样.

-   所以我们对$P(x)$的要求就是在$x=0$处其函数值以及各阶导数和$f(x)$的相等: $$
      P(0)=f(0),P'(0)=f'(0),\cdots, P^{(n)}(0)=f^{(n)}(0).
      $$
:::

::: {.callout-note collapse="true" icon="true"}
## $P(x)$怎么求?

根据导数相等, 待定系数法

-   注意到$P_n^{(k)}(0)=k!a_k,$ 所以用待定系数法就可以解出$P_n(x)$的各个系数.

-   $$ a_k=\frac{f^{(k)}(0)}{k!}, k=0, 1, 2,\cdot, n. $$

-   这样就确定了$f(x)$的近似函数 $$f(x)=\underbrace{ f(0)+f'(0)x+\frac{f^{(2)}(0)}{2!}x^2+\cdots+\frac{f^{(n)}(0)}{n!}x^n}+R(x). $$
:::

# 误差函数$R(x)$

::: {.callout-warning collapse="true" icon="true"}
## $R(x)$为什么是$f(x)$的次要部分?是误差?

估计误差

-   根据公式, 两个函数相减, 就得到余项(误差): $$
      R(x)=f(x)-P(x).
      $$

-   $R(x)$是不是次要部分, 能不能忽略需要我们仔细的估计它的大小.

-   根据$P(x)$的要求, 有$R^{(k)}(0)=0, k=0,1,\cdots, n.$ 对$f(x)$和\$ x\^n\$用洛必达法则得到皮亚诺型余项 $$
      \lim_{x\rightarrow 0}\frac{R(x)}{x^{n}}=\lim_{x\rightarrow 0}\frac{R'(x)}{nx^{n-1}}=\cdots=\lim_{x\rightarrow 0}\frac{R^{(n)}(x)}{{n!}}=0, \quad \therefore\, R(x)=o(x^{n}).
      $$

-   说明$R(x)$是$x^{n}$的高阶无穷小, 在0的附近, 余项确实很小.

-   如果改用柯西中值定理可以得到更细致的估计

-   $$
      R(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}x^{n+1}.
    $$ 这称为拉格朗日型余项.

-   此时泰勒公式就可以写得很具体. $$\begin{aligned}
    f(x)&={ f(0)+f'(0)x+\frac{f^{(2)}(0)}{2!}x^2+\cdots+\frac{f^{(n)}(0)}{n!}x^n}+o(x^{n}),\notag\\
      f(x)&={ f(0)+f'(0)x+\frac{f^{(2)}(0)}{2!}x^2+\cdots+\frac{f^{(n)}(0)}{n!}x^n}+\frac{f^{(n+1)}(\xi)}{(n+1)!}x^{n+1}. 
    \end{aligned}$$
:::

::: {.callout-tip collapse="true" icon="true"}
## $R_n(x)$中, 要选$n=?$

根据误差要求确定$n$

-   研究问题时总是先固定$x$.

-   对于固定的$x$, 比如$x=0.01,$ 如果 $f^{(n+1)}(\xi)$有界, 则$n$越大, $R(x)$就越小. 因此用$P(x)$作为$f(x)$的近似值, 则误差$R(x)$可以满足给定的要求(误差越小, 可能$n$就选要大一点).

-   应用泰勒公式时, $n$的选择取决于一开始问题的要求, 要求误差小于$10^{-3}$ 还是$10^{-5}?$ 根据这个要求再来确定合适的$n$.
:::

# 间接法求$P(x)$

::: {.callout-important collapse="true" icon="true"}
## 为什么用间接法?

-   直接法是用各阶导数相等, 由于高阶导数不容易求, 这种方法不太实用.
:::

::: {.callout-important collapse="true" icon="true"}
## 如何用间接法?

-   根据泰勒公式的唯一性, 利用已经求得函数的泰勒公式和一些运算法则求泰勒公式.
:::

# 泰勒公式的条件

要得到泰勒公式, 需要$n+1$阶可导.

# 局部与整体

::: {.callout-tip collapse="true" icon="true"}
## 局部与整体

-   泰勒公式是研究函数在点0的附近的性质, 是关于局部性质的公式.

-   由于拉格朗日型余项给出了精细的误差估计. 如果对于很大的$x$, 误差也很小, 则此时泰勒公式仍旧可以使用, 就变成了一个较大区间上的公式.

-   对于指数函数和三角函数来说, 对所有的$x$都可以使用. 变成了一个整体性质的公式.

-   如果函数有各阶导数, 则这样的函数可以用它在0处的各阶导数来描述. 就是0点处的性质决定了其它点(某个区间内)处的性质(函数值).
:::

# 泰勒公式会失效与局限性

::: {.callout-note collapse="true" icon="true"}
## 失效

对$f(x)=\frac{1}{1-x}$, 有泰勒公式

$$  
f(x)= 1+x+x^2+\cdots+x^n+\frac{f^{(n+1)}(\xi)}{(n+1)!}x^{n+1}. 
$$

-   对于$x=3$, 这也是一个等式, $\xi$需要确定.

-   但此时$\frac{f^{(n+1)}(\xi)}{(n+1)!}x^{n+1}$很大了, 如果还用$1+x+x^2+\cdots+x^n$作为近似值, 则误差很大, 选再大的$n$误差也不会减少.

-   此时近似值没有任何意义了. 所以泰勒公式还有, 但没有什么用处, 失效了.
:::

# 泰勒公式的应用

::: {.callout-important collapse="true" icon="true"}
## 求极限

用皮亚诺余项就行, 应用下面的公式 $$
o(x^k)o(x^l)=o(x^{k+l}), \quad o(x^2)+o(x^3)= o(x^2), \quad o(5x^2)= o(x^2).
$$
:::

::: {.callout-caution collapse="true" icon="true"}
## 证明不等式

用拉格朗日型余项就行, 精确估计此余项的符号或大小.
:::
